import * as fs from 'node:fs';
import * as path from 'node:path';
import fg from 'fast-glob';

/**
 * 4-Tier Semantic Token Taxonomy Names
 */
export type TokenTierName = 'surfaces' | 'typography' | 'brand' | 'geometry';

/**
 * Representation of an individual design token.
 */
export interface DesignToken {
  name: string;
  tier: TokenTierName;
  defaultValue: string;
  description: string;
  value?: string;
  source?: string;
}

/**
 * Canonical Token Definition with metadata for recommendation matching.
 */
export interface CanonicalTokenDef {
  name: string;
  tier: TokenTierName;
  defaultValue: string;
  description: string;
  pixelEquivalent?: number;
  colorRgb?: [number, number, number];
  darkColorRgb?: [number, number, number];
}

/**
 * The Complete 4-Tier Semantic Token Catalog.
 */
export interface DesignTokenCatalog {
  tiers: {
    surfaces: DesignToken[];
    typography: DesignToken[];
    brand: DesignToken[];
    geometry: DesignToken[];
  };
  tokens: Record<string, DesignToken>;
  hasMissingTokens: boolean;
  missingTokens: string[];
  coveragePercent: number;
  detectedSources: string[];
}

/**
 * Result of validating a token catalog against 4-tier taxonomy rules.
 */
export interface TaxonomyValidationResult {
  valid: boolean;
  errors: string[];
  tierSummary: {
    surfaces: number;
    typography: number;
    brand: number;
    geometry: number;
  };
}

/**
 * Recommendation for replacing a raw style with a semantic design token.
 */
export interface TokenRecommendation {
  token: string;
  replacement: string;
  confidence: 'exact' | 'nearest' | 'heuristic';
  reason: string;
}

/**
 * Specific violation found during style extraction.
 */
export interface StyleViolation {
  type: 'color-hex' | 'color-rgb' | 'color-hsl' | 'spacing-magic' | 'radius-magic' | 'inline-literal';
  raw: string;
  property?: string;
  line: number;
  column: number;
  recommendation: TokenRecommendation;
}

/**
 * Report generated by extractRawStyles.
 */
export interface StyleExtractionReport {
  violations: StyleViolation[];
  totalViolations: number;
  byType: {
    hexColors: number;
    rgbColors: number;
    magicDimensions: number;
    inlineLiterals: number;
  };
  recommendedReplacements: Array<{
    original: string;
    suggestedToken: string;
    cssVar: string;
  }>;
}

/**
 * Canonical 4-Tier Semantic Design Token Taxonomy (20 canonical tokens).
 */
export const CANONICAL_DESIGN_TOKENS: CanonicalTokenDef[] = [
  // 1. Surfaces & Backgrounds
  {
    name: '--surface-canvas',
    tier: 'surfaces',
    defaultValue: '#ffffff',
    description: 'Canvas & base application background',
    colorRgb: [255, 255, 255],
    darkColorRgb: [15, 23, 42],
  },
  {
    name: '--surface-card',
    tier: 'surfaces',
    defaultValue: '#f8fafc',
    description: 'Card & container surface background',
    colorRgb: [248, 250, 252],
    darkColorRgb: [30, 41, 59], // #1e293b
  },
  {
    name: '--surface-elevated',
    tier: 'surfaces',
    defaultValue: '#ffffff',
    description: 'Elevated surfaces, dropdowns, dialogs, and popovers',
    colorRgb: [255, 255, 255],
    darkColorRgb: [51, 65, 85], // #334155
  },
  {
    name: '--surface-sunken',
    tier: 'surfaces',
    defaultValue: '#f1f5f9',
    description: 'Sunken wells, inset controls, and input backgrounds',
    colorRgb: [241, 245, 249],
    darkColorRgb: [2, 6, 23], // #020617
  },

  // 2. Content & Typography
  {
    name: '--text-primary',
    tier: 'typography',
    defaultValue: '#0f172a',
    description: 'Primary text, headings, and high-emphasis content',
    colorRgb: [15, 23, 42],
    darkColorRgb: [248, 250, 252],
  },
  {
    name: '--text-secondary',
    tier: 'typography',
    defaultValue: '#475569',
    description: 'Secondary text, subheadings, and medium-emphasis content',
    colorRgb: [71, 85, 105],
    darkColorRgb: [148, 163, 184],
  },
  {
    name: '--text-muted',
    tier: 'typography',
    defaultValue: '#94a3b8',
    description: 'Muted text, placeholders, disabled elements, and captions',
    colorRgb: [148, 163, 184],
    darkColorRgb: [100, 116, 139],
  },
  {
    name: '--text-accent',
    tier: 'typography',
    defaultValue: '#2563eb',
    description: 'Accent text, links, highlights, and active items',
    colorRgb: [37, 99, 235],
    darkColorRgb: [96, 165, 250],
  },

  // 3. Brand & State
  {
    name: '--brand-primary',
    tier: 'brand',
    defaultValue: '#2563eb',
    description: 'Primary brand identity and call-to-action color',
    colorRgb: [37, 99, 235],
  },
  {
    name: '--brand-secondary',
    tier: 'brand',
    defaultValue: '#4f46e5',
    description: 'Secondary brand identity and complementary interactive color',
    colorRgb: [79, 70, 229],
  },
  {
    name: '--state-success',
    tier: 'brand',
    defaultValue: '#16a34a',
    description: 'Positive state, success confirmations, and approved badges',
    colorRgb: [22, 163, 74],
  },
  {
    name: '--state-warning',
    tier: 'brand',
    defaultValue: '#ca8a04',
    description: 'Warning state, caution alerts, and pending statuses',
    colorRgb: [202, 138, 4],
  },
  {
    name: '--state-danger',
    tier: 'brand',
    defaultValue: '#dc2626',
    description: 'Danger state, critical errors, and destructive actions',
    colorRgb: [220, 38, 38],
  },

  // 4. Geometry & Spacing
  {
    name: '--radius-sm',
    tier: 'geometry',
    defaultValue: '4px',
    description: 'Small border radius for badges, tags, and small buttons',
    pixelEquivalent: 4,
  },
  {
    name: '--radius-md',
    tier: 'geometry',
    defaultValue: '8px',
    description: 'Medium border radius for cards, inputs, and standard buttons',
    pixelEquivalent: 8,
  },
  {
    name: '--radius-lg',
    tier: 'geometry',
    defaultValue: '16px',
    description: 'Large border radius for modals, overlays, and large cards',
    pixelEquivalent: 16,
  },
  {
    name: '--space-2',
    tier: 'geometry',
    defaultValue: '2px',
    description: 'Micro spacing unit (2px / 0.125rem)',
    pixelEquivalent: 2,
  },
  {
    name: '--space-4',
    tier: 'geometry',
    defaultValue: '4px',
    description: 'Compact spacing unit (4px / 0.25rem)',
    pixelEquivalent: 4,
  },
  {
    name: '--space-8',
    tier: 'geometry',
    defaultValue: '8px',
    description: 'Standard medium spacing unit (8px / 0.5rem)',
    pixelEquivalent: 8,
  },
  {
    name: '--space-16',
    tier: 'geometry',
    defaultValue: '16px',
    description: 'Standard large spacing unit (16px / 1rem)',
    pixelEquivalent: 16,
  },
];

const TOKEN_ALIASES: Record<string, string> = {
  '--canvas': '--surface-canvas',
  '--bg-canvas': '--surface-canvas',
  '--background': '--surface-canvas',
  '--bg': '--surface-canvas',
  '--card': '--surface-card',
  '--bg-card': '--surface-card',
  '--surface': '--surface-card',
  '--elevated': '--surface-elevated',
  '--popover': '--surface-elevated',
  '--modal': '--surface-elevated',
  '--sunken': '--surface-sunken',
  '--inset': '--surface-sunken',
  '--input-bg': '--surface-sunken',
  '--text': '--text-primary',
  '--foreground': '--text-primary',
  '--text-body': '--text-primary',
  '--text-sub': '--text-secondary',
  '--muted': '--text-muted',
  '--text-disabled': '--text-muted',
  '--accent': '--text-accent',
  '--primary': '--brand-primary',
  '--color-primary': '--brand-primary',
  '--secondary': '--brand-secondary',
  '--color-secondary': '--brand-secondary',
  '--success': '--state-success',
  '--color-success': '--state-success',
  '--warning': '--state-warning',
  '--color-warning': '--state-warning',
  '--danger': '--state-danger',
  '--error': '--state-danger',
  '--color-danger': '--state-danger',
  '--color-error': '--state-danger',
  '--radius': '--radius-md',
  '--border-radius': '--radius-md',
};

function parseHexColor(hex: string): [number, number, number] | null {
  const clean = hex.startsWith('#') ? hex.slice(1) : hex;
  if (clean.length === 3 || clean.length === 4) {
    const r = parseInt(clean[0] + clean[0], 16);
    const g = parseInt(clean[1] + clean[1], 16);
    const b = parseInt(clean[2] + clean[2], 16);
    return isNaN(r) || isNaN(g) || isNaN(b) ? null : [r, g, b];
  }
  if (clean.length >= 6) {
    const r = parseInt(clean.slice(0, 2), 16);
    const g = parseInt(clean.slice(2, 4), 16);
    const b = parseInt(clean.slice(4, 6), 16);
    return isNaN(r) || isNaN(g) || isNaN(b) ? null : [r, g, b];
  }
  return null;
}

function parseRgbColor(rgbStr: string): [number, number, number] | null {
  const match = rgbStr.match(/rgba?\s*\(\s*(\d+)\s*,\s*(\d+)\s*,\s*(\d+)/i);
  if (!match) return null;
  return [parseInt(match[1], 10), parseInt(match[2], 10), parseInt(match[3], 10)];
}

function hslToRgb(h: number, s: number, l: number): [number, number, number] {
  s /= 100;
  l /= 100;
  const k = (n: number) => (n + h / 30) % 12;
  const a = s * Math.min(l, 1 - l);
  const f = (n: number) =>
    l - a * Math.max(-1, Math.min(k(n) - 3, Math.min(9 - k(n), 1)));
  return [Math.round(255 * f(0)), Math.round(255 * f(8)), Math.round(255 * f(4))];
}

function parseHslColor(hslStr: string): [number, number, number] | null {
  const match = hslStr.match(/hsla?\s*\(\s*(\d+)\s*,\s*(\d+)%?\s*,\s*(\d+)%?/i);
  if (!match) return null;
  const h = parseInt(match[1], 10);
  const s = parseInt(match[2], 10);
  const l = parseInt(match[3], 10);
  return hslToRgb(h, s, l);
}

function colorDistance(c1: [number, number, number], c2: [number, number, number]): number {
  return Math.sqrt(
    Math.pow(c1[0] - c2[0], 2) +
    Math.pow(c1[1] - c2[1], 2) +
    Math.pow(c1[2] - c2[2], 2)
  );
}

function findNearestColorToken(
  rgb: [number, number, number],
  property?: string
): { token: CanonicalTokenDef; distance: number } {
  const candidates = CANONICAL_DESIGN_TOKENS.filter((t) => t.colorRgb);

  const propLower = (property || '').toLowerCase();
  const isBackground = /background|bg|surface/.test(propLower);
  const isText = /color|text|font/.test(propLower) && !isBackground;

  let bestToken = candidates[0];
  let minDistance = Infinity;

  for (const candidate of candidates) {
    if (!candidate.colorRgb) continue;
    let dist = colorDistance(rgb, candidate.colorRgb);
    if (candidate.darkColorRgb) {
      const darkDist = colorDistance(rgb, candidate.darkColorRgb);
      if (darkDist < dist) dist = darkDist;
    }

    if (isBackground) {
      if (candidate.tier === 'surfaces') dist *= 0.8;
      if (candidate.tier === 'typography') dist *= 1.3;
    } else if (isText) {
      if (candidate.tier === 'typography') dist *= 0.8;
      if (candidate.tier === 'surfaces') dist *= 1.3;
    }

    if (dist < minDistance) {
      minDistance = dist;
      bestToken = candidate;
    }
  }

  return { token: bestToken, distance: minDistance };
}

function findNearestSpacingToken(pixelValue: number): { token: CanonicalTokenDef; diff: number } {
  const spacingTokens = CANONICAL_DESIGN_TOKENS.filter(
    (t) => t.name.startsWith('--space-') && t.pixelEquivalent !== undefined
  );
  let best = spacingTokens[0];
  let minDiff = Infinity;
  for (const t of spacingTokens) {
    const diff = Math.abs(pixelValue - t.pixelEquivalent!);
    if (diff <= minDiff) {
      minDiff = diff;
      best = t;
    }
  }
  return { token: best, diff: minDiff };
}

function findNearestRadiusToken(pixelValue: number): { token: CanonicalTokenDef; diff: number } {
  const radiusTokens = CANONICAL_DESIGN_TOKENS.filter(
    (t) => t.name.startsWith('--radius-') && t.pixelEquivalent !== undefined
  );
  let best = radiusTokens[0];
  let minDiff = Infinity;
  for (const t of radiusTokens) {
    const diff = Math.abs(pixelValue - t.pixelEquivalent!);
    if (diff <= minDiff) {
      minDiff = diff;
      best = t;
    }
  }
  return { token: best, diff: minDiff };
}

/**
 * TokenSynthesizer: Enforces 4-tier semantic design token taxonomy,
 * extracts raw styles with token recommendations, and generates
 * foundational Design System tracks when tokens are missing.
 */
export class TokenSynthesizer {
  /**
   * Returns the list of all canonical token definitions.
   */
  public static getCanonicalTokens(): CanonicalTokenDef[] {
    return [...CANONICAL_DESIGN_TOKENS];
  }

  /**
   * Synthesizes design tokens by scanning the given project root.
   * If tokens are missing or partial, synthesizes the complete 4-tier taxonomy.
   */
  public async synthesizeTokens(projectRoot: string): Promise<DesignTokenCatalog> {
    const discoveredTokens: Record<string, { value: string; source: string }> = {};
    const detectedSourcesSet = new Set<string>();

    if (fs.existsSync(projectRoot)) {
      try {
        const pattern = [
          '**/*.css',
          '**/*.scss',
          '**/*.less',
          '**/tailwind.config.{js,cjs,mjs,ts}',
          '**/theme.json',
          '**/tokens.json',
          'product/design-system/*.json',
        ];

        const files = await fg(pattern, {
          cwd: projectRoot,
          absolute: false,
          ignore: [
            '**/node_modules/**',
            '**/dist/**',
            '**/.git/**',
            '**/.next/**',
            '**/build/**',
            '**/out/**',
          ],
        });

        for (const file of files) {
          const fullPath = path.join(projectRoot, file);
          let content = '';
          try {
            content = fs.readFileSync(fullPath, 'utf-8');
          } catch {
            continue;
          }

          if (file.endsWith('.json')) {
            try {
              const parsed = JSON.parse(content);
              this.extractTokensFromJson(parsed, file, discoveredTokens, detectedSourcesSet);
            } catch {
              // Ignore corrupt json
            }
          } else {
            // Strip CSS comments
            const cleanContent = content.replace(/\/\*[\s\S]*?\*\//g, '');
            const cssVarRegex = /(--[a-zA-Z0-9_-]+)\s*:\s*([^;}\n]+)/g;
            let match: RegExpExecArray | null;
            while ((match = cssVarRegex.exec(cleanContent)) !== null) {
              const rawName = match[1].trim();
              const rawVal = match[2].trim();
              discoveredTokens[rawName] = { value: rawVal, source: file };
              detectedSourcesSet.add(file);

              if (TOKEN_ALIASES[rawName]) {
                const canonicalName = TOKEN_ALIASES[rawName];
                if (!discoveredTokens[canonicalName]) {
                  discoveredTokens[canonicalName] = { value: rawVal, source: file };
                }
              }
            }
          }
        }
      } catch {
        // Fallback gracefully on glob error
      }
    }

    // Build the 4-tier catalog
    const surfaces: DesignToken[] = [];
    const typography: DesignToken[] = [];
    const brand: DesignToken[] = [];
    const geometry: DesignToken[] = [];
    const tokens: Record<string, DesignToken> = {};
    const missingTokens: string[] = [];

    for (const def of CANONICAL_DESIGN_TOKENS) {
      const discovered = discoveredTokens[def.name];
      const isMissing = !discovered;
      if (isMissing) {
        missingTokens.push(def.name);
      }

      const token: DesignToken = {
        name: def.name,
        tier: def.tier,
        defaultValue: def.defaultValue,
        description: def.description,
        value: discovered ? discovered.value : def.defaultValue,
        source: discovered ? discovered.source : 'synthesized',
      };

      tokens[def.name] = token;

      switch (def.tier) {
        case 'surfaces':
          surfaces.push(token);
          break;
        case 'typography':
          typography.push(token);
          break;
        case 'brand':
          brand.push(token);
          break;
        case 'geometry':
          geometry.push(token);
          break;
      }
    }

    const totalTokens = CANONICAL_DESIGN_TOKENS.length;
    const foundCount = totalTokens - missingTokens.length;
    const coveragePercent = Math.round((foundCount / totalTokens) * 100);

    return {
      tiers: {
        surfaces,
        typography,
        brand,
        geometry,
      },
      tokens,
      hasMissingTokens: missingTokens.length > 0,
      missingTokens,
      coveragePercent,
      detectedSources: Array.from(detectedSourcesSet),
    };
  }

  private extractTokensFromJson(
    obj: any,
    file: string,
    discovered: Record<string, { value: string; source: string }>,
    sources: Set<string>
  ) {
    if (!obj || typeof obj !== 'object') return;

    for (const [key, val] of Object.entries(obj)) {
      if (typeof val === 'string') {
        const tokenName = key.startsWith('--') ? key : `--${key}`;
        discovered[tokenName] = { value: val, source: file };
        sources.add(file);
        if (TOKEN_ALIASES[tokenName]) {
          discovered[TOKEN_ALIASES[tokenName]] = { value: val, source: file };
        }
      } else if (typeof val === 'object') {
        this.extractTokensFromJson(val, file, discovered, sources);
      }
    }
  }

  /**
   * Validates that a catalog complies with the 4-tier semantic taxonomy.
   */
  public validateTaxonomy(catalog: DesignTokenCatalog): TaxonomyValidationResult {
    const errors: string[] = [];
    const tierSummary = {
      surfaces: 0,
      typography: 0,
      brand: 0,
      geometry: 0,
    };

    if (!catalog || !catalog.tiers) {
      return {
        valid: false,
        errors: ['Catalog or catalog.tiers is missing or undefined.'],
        tierSummary,
      };
    }

    const expectedTiers: TokenTierName[] = ['surfaces', 'typography', 'brand', 'geometry'];
    for (const tierName of expectedTiers) {
      const list = catalog.tiers[tierName];
      if (!Array.isArray(list)) {
        errors.push(`Missing tier category array: tiers.${tierName}`);
      } else {
        tierSummary[tierName] = list.length;
      }
    }

    for (const def of CANONICAL_DESIGN_TOKENS) {
      const inTokens = catalog.tokens && catalog.tokens[def.name];
      const inTier = catalog.tiers[def.tier]?.some((t) => t.name === def.name);
      if (!inTokens) {
        errors.push(`Missing canonical token in catalog.tokens: ${def.name}`);
      }
      if (!inTier) {
        errors.push(`Missing canonical token in catalog.tiers.${def.tier}: ${def.name}`);
      }
    }

    return {
      valid: errors.length === 0,
      errors,
      tierSummary,
    };
  }

  /**
   * Extracts raw styles (hex codes, RGB, magic pixel values, inline style literals)
   * from a code snippet and recommends mapping to nearest semantic tokens.
   */
  public extractRawStyles(codeSnippet: string): StyleExtractionReport {
    const violations: StyleViolation[] = [];
    let hexCount = 0;
    let rgbCount = 0;
    let magicDimensionsCount = 0;
    let inlineLiteralsCount = 0;

    const replacementsMap = new Map<string, { suggestedToken: string; cssVar: string }>();

    const lines = codeSnippet.split('\n');

    for (let lineIdx = 0; lineIdx < lines.length; lineIdx++) {
      const line = lines[lineIdx];
      const lineNum = lineIdx + 1;

      // 1. Magic Pixel Values (Spacing & Radius)
      // Check CSS / JSX property declarations with pixel dimensions
      const declRegex = /(padding|margin|gap|top|bottom|left|right|borderRadius|border-radius)[a-zA-Z-]*\s*:\s*['"]?([0-9.]+(?:px)?)['"]?/gi;
      let declMatch: RegExpExecArray | null;
      while ((declMatch = declRegex.exec(line)) !== null) {
        const propName = declMatch[1];
        const rawVal = declMatch[2];
        const fullDecl = declMatch[0];
        const numVal = parseFloat(rawVal.replace(/px/i, ''));

        if (!isNaN(numVal)) {
          magicDimensionsCount++;
          const isRadius = /radius/i.test(propName);
          const colIdx = declMatch.index + 1;

          if (isRadius) {
            const nearest = findNearestRadiusToken(numVal);
            const tokenName = nearest.token.name;
            const cssVar = `var(${tokenName})`;

            violations.push({
              type: 'radius-magic',
              raw: fullDecl,
              property: propName,
              line: lineNum,
              column: colIdx,
              recommendation: {
                token: tokenName,
                replacement: cssVar,
                confidence: nearest.diff === 0 ? 'exact' : 'nearest',
                reason: `${numVal}px is closest to ${tokenName} (${nearest.token.pixelEquivalent}px)`,
              },
            });

            replacementsMap.set(fullDecl, { suggestedToken: tokenName, cssVar });
            replacementsMap.set(`${numVal}px`, { suggestedToken: tokenName, cssVar });
          } else {
            const nearest = findNearestSpacingToken(numVal);
            const tokenName = nearest.token.name;
            const cssVar = `var(${tokenName})`;

            violations.push({
              type: 'spacing-magic',
              raw: fullDecl,
              property: propName,
              line: lineNum,
              column: colIdx,
              recommendation: {
                token: tokenName,
                replacement: cssVar,
                confidence: nearest.diff === 0 ? 'exact' : 'nearest',
                reason: `${numVal}px is closest to ${tokenName} (${nearest.token.pixelEquivalent}px)`,
              },
            });

            replacementsMap.set(fullDecl, { suggestedToken: tokenName, cssVar });
            replacementsMap.set(`${numVal}px`, { suggestedToken: tokenName, cssVar });
          }
        }
      }

      // 2. Check Tailwind arbitrary brackets: p-[13px], rounded-[7px], etc.
      const twRegex = /\b(p|m|gap|px|py|pt|pb|pl|pr|rounded)-\[(\d+(?:\.\d+)?(?:px)?)\]/gi;
      let twMatch: RegExpExecArray | null;
      while ((twMatch = twRegex.exec(line)) !== null) {
        const prefix = twMatch[1];
        const rawVal = twMatch[2];
        const fullClass = twMatch[0];
        const numVal = parseFloat(rawVal.replace(/px/i, ''));

        if (!isNaN(numVal)) {
          magicDimensionsCount++;
          const isRadius = prefix === 'rounded';
          const colIdx = twMatch.index + 1;

          if (isRadius) {
            const nearest = findNearestRadiusToken(numVal);
            const tokenName = nearest.token.name;
            const cssVar = `var(${tokenName})`;

            violations.push({
              type: 'radius-magic',
              raw: fullClass,
              property: 'border-radius',
              line: lineNum,
              column: colIdx,
              recommendation: {
                token: tokenName,
                replacement: cssVar,
                confidence: nearest.diff === 0 ? 'exact' : 'nearest',
                reason: `${numVal}px is closest to ${tokenName} (${nearest.token.pixelEquivalent}px)`,
              },
            });

            replacementsMap.set(fullClass, { suggestedToken: tokenName, cssVar });
            replacementsMap.set(`${numVal}px`, { suggestedToken: tokenName, cssVar });
          } else {
            const nearest = findNearestSpacingToken(numVal);
            const tokenName = nearest.token.name;
            const cssVar = `var(${tokenName})`;

            violations.push({
              type: 'spacing-magic',
              raw: fullClass,
              property: 'spacing',
              line: lineNum,
              column: colIdx,
              recommendation: {
                token: tokenName,
                replacement: cssVar,
                confidence: nearest.diff === 0 ? 'exact' : 'nearest',
                reason: `${numVal}px is closest to ${tokenName} (${nearest.token.pixelEquivalent}px)`,
              },
            });

            replacementsMap.set(fullClass, { suggestedToken: tokenName, cssVar });
            replacementsMap.set(`${numVal}px`, { suggestedToken: tokenName, cssVar });
          }
        }
      }

      // 3. Raw Hex Colors (#1e293b, etc.)
      const hexRegex = /#([0-9a-fA-F]{8}|[0-9a-fA-F]{6}|[0-9a-fA-F]{3,4})\b/g;
      let hexMatch: RegExpExecArray | null;
      while ((hexMatch = hexRegex.exec(line)) !== null) {
        const rawHex = hexMatch[0];
        const colIdx = hexMatch.index + 1;
        const rgb = parseHexColor(rawHex);

        if (rgb) {
          hexCount++;
          const property = this.inferPropertyContext(line, hexMatch.index);
          const nearest = findNearestColorToken(rgb, property);

          const tokenName = nearest.token.name;
          const cssVar = `var(${tokenName})`;

          violations.push({
            type: 'color-hex',
            raw: rawHex,
            property,
            line: lineNum,
            column: colIdx,
            recommendation: {
              token: tokenName,
              replacement: cssVar,
              confidence: nearest.distance === 0 ? 'exact' : 'nearest',
              reason: `${rawHex} matches ${tokenName} (color distance: ${Math.round(nearest.distance)})`,
            },
          });

          replacementsMap.set(rawHex, { suggestedToken: tokenName, cssVar });
        }
      }

      // 4. RGB / RGBA / HSL Colors
      const rgbRegex = /(rgba?|hsla?)\s*\(([^)]+)\)/gi;
      let rgbMatch: RegExpExecArray | null;
      while ((rgbMatch = rgbRegex.exec(line)) !== null) {
        const rawColor = rgbMatch[0];
        const colIdx = rgbMatch.index + 1;
        const fnName = rgbMatch[1].toLowerCase();

        let rgb: [number, number, number] | null = null;
        if (fnName.startsWith('rgb')) {
          rgb = parseRgbColor(rawColor);
        } else if (fnName.startsWith('hsl')) {
          rgb = parseHslColor(rawColor);
        }

        if (rgb) {
          rgbCount++;
          const property = this.inferPropertyContext(line, rgbMatch.index);
          const nearest = findNearestColorToken(rgb, property);

          const tokenName = nearest.token.name;
          const cssVar = `var(${tokenName})`;

          violations.push({
            type: fnName.startsWith('rgb') ? 'color-rgb' : 'color-hsl',
            raw: rawColor,
            property,
            line: lineNum,
            column: colIdx,
            recommendation: {
              token: tokenName,
              replacement: cssVar,
              confidence: nearest.distance === 0 ? 'exact' : 'nearest',
              reason: `${rawColor} matches ${tokenName} (color distance: ${Math.round(nearest.distance)})`,
            },
          });

          replacementsMap.set(rawColor, { suggestedToken: tokenName, cssVar });
        }
      }

      // 5. Inline Style Literals in JSX/HTML
      const inlineStyleRegex = /style\s*=\s*(?:\{\{([\s\S]*?)\}\}|"([^"]*)"|'([^']*)')/g;
      let inlineMatch: RegExpExecArray | null;
      while ((inlineMatch = inlineStyleRegex.exec(line)) !== null) {
        inlineLiteralsCount++;
        const raw = inlineMatch[0];
        violations.push({
          type: 'inline-literal',
          raw,
          line: lineNum,
          column: inlineMatch.index + 1,
          recommendation: {
            token: 'refactor-inline-styles',
            replacement: 'Extract inline styles to CSS class or design tokens',
            confidence: 'heuristic',
            reason: 'Inline style literals violate Design OS Hit-Testing and Semantic Binding Dogma. Bind to semantic CSS variables or tokens instead.',
          },
        });
      }
    }

    const recommendedReplacements = Array.from(replacementsMap.entries()).map(([original, rec]) => ({
      original,
      suggestedToken: rec.suggestedToken,
      cssVar: rec.cssVar,
    }));

    return {
      violations,
      totalViolations: violations.length,
      byType: {
        hexColors: hexCount,
        rgbColors: rgbCount,
        magicDimensions: magicDimensionsCount,
        inlineLiterals: inlineLiteralsCount,
      },
      recommendedReplacements,
    };
  }

  private inferPropertyContext(line: string, matchIndex: number): string | undefined {
    const beforeMatch = line.slice(0, matchIndex);
    const propMatch = beforeMatch.match(/([a-zA-Z-]+)\s*:\s*['"]?$/);
    if (propMatch) {
      return propMatch[1];
    }
    const twMatch = beforeMatch.match(/(bg|text|border)-\[$/);
    if (twMatch) {
      if (twMatch[1] === 'bg') return 'background-color';
      if (twMatch[1] === 'text') return 'color';
      if (twMatch[1] === 'border') return 'border-color';
    }
    return undefined;
  }

  /**
   * Generates standard CSS variable declarations for the 4-tier token taxonomy.
   */
  public generateCssVariables(catalog?: DesignTokenCatalog): string {
    const tokens = catalog ? Object.values(catalog.tokens) : CANONICAL_DESIGN_TOKENS;

    const surfaces = tokens.filter((t) => t.tier === 'surfaces');
    const typography = tokens.filter((t) => t.tier === 'typography');
    const brand = tokens.filter((t) => t.tier === 'brand');
    const geometry = tokens.filter((t) => t.tier === 'geometry');

    const lines: string[] = [
      '/**',
      ' * Foundational 4-Tier Semantic Design Tokens',
      ' * Scaffolding generated by Superconductor TokenSynthesizer',
      ' */',
      ':root {',
      '  /* 1. Surfaces & Backgrounds */',
    ];

    for (const t of surfaces) {
      lines.push(`  ${t.name}: ${(t as any).value || t.defaultValue};`);
    }

    lines.push('', '  /* 2. Content & Typography */');
    for (const t of typography) {
      lines.push(`  ${t.name}: ${(t as any).value || t.defaultValue};`);
    }

    lines.push('', '  /* 3. Brand & State */');
    for (const t of brand) {
      lines.push(`  ${t.name}: ${(t as any).value || t.defaultValue};`);
    }

    lines.push('', '  /* 4. Geometry & Spacing */');
    for (const t of geometry) {
      lines.push(`  ${t.name}: ${(t as any).value || t.defaultValue};`);
    }

    lines.push('}');
    return lines.join('\n');
  }

  /**
   * Scaffolds a foundational Design System Track when a project lacks tokens.
   */
  public generateDesignSystemTrack(catalog: DesignTokenCatalog): {
    specMarkdown: string;
    planMarkdown: string;
  } {
    const missingList = catalog.missingTokens.length > 0 ? catalog.missingTokens.join(', ') : 'None';
    const sourcesList = catalog.detectedSources.length > 0 ? catalog.detectedSources.join(', ') : 'None (synthesized defaults)';

    const specMarkdown = `# Track Specification: Scaffolding Foundational Semantic Design Tokens

## Background, Problem & Architectural Rationale
During visual wireframing, UI prototyping, and component development, hardcoded CSS literals, magic pixel dimensions, and arbitrary hex codes introduce visual inconsistencies and prevent cohesive theming.
In accordance with **ADR 0002 (Automated Token Synthesis & Upfront Localization)**, all components and live proposal drafts must bind strictly to the 4-tier semantic design token taxonomy.

### Current Token Audit Status
- **Coverage:** ${catalog.coveragePercent}%
- **Identified Missing Tokens:** ${missingList}
- **Detected Token Sources:** ${sourcesList}

## 4-Tier Semantic Token Taxonomy
The design system enforces four mandatory tiers of semantic tokens:

1. **Surfaces & Backgrounds**:
   - \`--surface-canvas\`: Canvas and base application background
   - \`--surface-card\`: Standard card and container surface
   - \`--surface-elevated\`: Elevated modals, dropdowns, and popovers
   - \`--surface-sunken\`: Sunken wells, inputs, and recessed panels

2. **Content & Typography**:
   - \`--text-primary\`: Primary body text and headers
   - \`--text-secondary\`: Secondary captions and labels
   - \`--text-muted\`: Muted placeholders and disabled states
   - \`--text-accent\`: Accent links and focused interactive text

3. **Brand & State**:
   - \`--brand-primary\`: Primary brand identity color
   - \`--brand-secondary\`: Secondary complementary brand accent
   - \`--state-success\`: Positive confirmations and success indicators
   - \`--state-warning\`: Caution alerts and warning statuses
   - \`--state-danger\`: Critical errors and destructive action indicators

4. **Geometry & Spacing**:
   - \`--radius-sm\`, \`--radius-md\`, \`--radius-lg\`: Semantic border radii (4px, 8px, 16px)
   - \`--space-2\`, \`--space-4\`, \`--space-8\`, \`--space-16\`: Micro and layout spacing units (2px, 4px, 8px, 16px)

## Functional Requirements
- **FR-1**: Generate \`src/theme/tokens.css\` exporting all 20 canonical design tokens with light and dark mode mappings.
- **FR-2**: Enforce 4-tier taxonomy structure across the codebase via automated validation tests.
- **FR-3**: Provide theme provider or entry point bindings in \`src/theme/index.ts\` for downstream component consumption.

## Non-Functional Requirements
- **Zero-Config**: Can be consumed directly by modern CSS, Tailwind, or CSS-in-JS tooling without additional build dependencies.
- **Confinement**: All token definitions isolated in \`src/theme/\`.
- **Dogma Compliance**: Strict adherence to Design OS Hit-Testing and Semantic Binding Dogma.

## Acceptance Criteria
- **AC-1**: All 20 semantic design tokens exist in \`src/theme/tokens.css\` and resolve in both \`:root\` and dark themes.
- **AC-2**: Automated unit tests in \`tests/theme/tokens.test.ts\` pass and verify all 4 tiers.
- **AC-3**: Token exports in \`src/theme/index.ts\` enable direct programmatic consumption.
`;

    const planMarkdown = `# Implementation Plan: Foundational Semantic Design Tokens Scaffolding

**Status:** [ ]
**Phase:** design-tokens

## Phase 0: Semantic Design Token Definition & Token Scaffolding

- [ ] Task: Scaffold Semantic Design Tokens [TIER-1] [AGENT:superconductor-processor] [DOMAIN:design-tokens]
    CREATES: src/theme/tokens.css
    PROTECTED: package.json
    INVARIANT_AFTER: "All 4 tiers of canonical semantic tokens MUST be defined in :root with valid fallback values."
    - [ ] Create src/theme/tokens.css declaring 20 canonical semantic tokens
    - [ ] Bind fallback color and spacing variables for Surfaces, Typography, Brand, and Geometry
    - [ ] Add root and dark mode theme selectors

- [ ] Task: Create Design Token Contract Verification Suite [TIER-2] [AGENT:superconductor-processor] [DOMAIN:design-tokens]
    CREATES: tests/theme/tokens.test.ts
    PROTECTED: src/theme/tokens.css
    INVARIANT_AFTER: "Token test suite MUST verify all 20 canonical design tokens exist and resolve."
    - [ ] Add automated token resolution tests
    - [ ] Verify 4-tier taxonomy structure

## Phase 1: Application Entry Wiring & Token Export

- [ ] Task: Wire Tokens into Application Entry [TIER-1] [AGENT:superconductor-processor] [DOMAIN:design-tokens]
    CREATES: src/theme/index.ts
    PROTECTED: src/theme/tokens.css
    INVARIANT_AFTER: "Theme module MUST export token helper utilities and import tokens.css."
    - [ ] Create src/theme/index.ts module entry point
    - [ ] Export CSS variable references and token catalog
`;

    return { specMarkdown, planMarkdown };
  }
}
