import * as path from 'path';
import { resolveProjectRoot } from './utils/resolve-project-root.js';
import { IntelligenceAuditReporter, AuditReport } from './audit-reporter.js';

export interface PreflightCheckResult {
  report: AuditReport;
  formattedBanner: string;
  isMismatch: boolean;
}

export class IntelligencePreflightCheck {
  /**
   * Executes a preflight check of the Superconductor intelligence subsystem.
   *
   * 1. Resolves `projectRoot` via `resolveProjectRoot(projectRoot)`.
   * 2. Resolves `outputDir` as `outputDir ?? path.join(resolvedProjectRoot, 'superconductor', 'intelligence')`.
   * 3. Calls `IntelligenceAuditReporter.report(resolvedOutputDir, resolvedProjectRoot)`.
   * 4. Formats a status banner strictly conforming to UX-2 standard.
   *
   * @param projectRoot - Optional workspace root (defaults to git root / cwd).
   * @param outputDir - Optional intelligence output directory (defaults to <projectRoot>/superconductor/intelligence).
   * @returns PreflightCheckResult containing report, formattedBanner, and isMismatch flag.
   */
  public static run(projectRoot?: string, outputDir?: string): PreflightCheckResult {
    const resolvedProjectRoot = resolveProjectRoot(projectRoot);
    const resolvedOutputDir = outputDir ?? path.join(resolvedProjectRoot, 'superconductor', 'intelligence');

    const report = IntelligenceAuditReporter.report(resolvedOutputDir, resolvedProjectRoot);
    const isMismatch = report.status === 'MISMATCH';

    let formattedBanner: string;
    if (isMismatch) {
      const statusLine = IntelligencePreflightCheck.formatStatusLine(report);
      const indexed = report.manifest_project_root ?? 'unknown';
      const current = report.project_root;
      formattedBanner = [
        statusLine,
        '⚠️  Intelligence Directory Mismatch Detected!',
        `   Indexed directory:  ${indexed}`,
        `   Current workspace:  ${current}`,
        'Triggering automatic re-scan against current workspace...',
      ].join('\n');
    } else {
      formattedBanner = IntelligencePreflightCheck.formatStatusLine(report);
    }

    return {
      report,
      formattedBanner,
      isMismatch,
    };
  }

  /**
   * Formats a single-line status summary for the given AuditReport according to UX-2 standard:
   * - LIVE:     `[superconductor] Intelligence: LIVE | Project: <name> | SHA: <sha7> | Age: <Xh>`
   * - MISMATCH: `[superconductor] Intelligence: MISMATCH | Indexed: <manifest_project_root> | Current: <project_root>`
   * - STALE:    `[superconductor] Intelligence: STALE | Project: <name> | SHA: <sha7> | Behind: <N> commits`
   * - NONE:     `[superconductor] Intelligence: NONE | Run: /superconductor:setup to index this project`
   *
   * @param report - The AuditReport generated by IntelligenceAuditReporter.
   * @returns A single-line status summary string.
   */
  public static formatStatusLine(report: AuditReport): string {
    const status = report.status;
    const name = IntelligencePreflightCheck._resolveProjectName(report);
    const sha7 = IntelligencePreflightCheck._resolveSha7(report);
    const ageHours = IntelligencePreflightCheck._resolveAgeHours(report);
    const commitsBehind = IntelligencePreflightCheck._resolveCommitsBehind(report);

    switch (status) {
      case 'LIVE':
        return `[superconductor] Intelligence: LIVE | Project: ${name} | SHA: ${sha7} | Age: ${ageHours}h`;

      case 'MISMATCH': {
        const indexed = report.manifest_project_root ?? 'unknown';
        const current = report.project_root;
        return `[superconductor] Intelligence: MISMATCH | Indexed: ${indexed} | Current: ${current}`;
      }

      case 'STALE':
        return `[superconductor] Intelligence: STALE | Project: ${name} | SHA: ${sha7} | Behind: ${commitsBehind} commits`;

      case 'NONE':
      default:
        return '[superconductor] Intelligence: NONE | Run: /superconductor:setup to index this project';
    }
  }

  /**
   * Instance method delegating to static `run`.
   */
  public run(projectRoot?: string, outputDir?: string): PreflightCheckResult {
    return IntelligencePreflightCheck.run(projectRoot, outputDir);
  }

  /**
   * Instance method delegating to static `formatStatusLine`.
   */
  public formatStatusLine(report: AuditReport): string {
    return IntelligencePreflightCheck.formatStatusLine(report);
  }

  private static _resolveProjectName(report: AuditReport): string {
    if ((report as any).projectName) return (report as any).projectName;
    if ((report as any).project_name) return (report as any).project_name;
    if (report.project_root) {
      const base = path.basename(report.project_root);
      if (base) return base;
      return report.project_root;
    }
    return 'unknown';
  }

  private static _resolveSha7(report: AuditReport): string {
    const headCommit = report.head_commit;
    if (!headCommit || headCommit === 'unknown') {
      return 'unknown';
    }
    return headCommit.length > 7 ? headCommit.slice(0, 7) : headCommit;
  }

  private static _resolveAgeHours(report: AuditReport): number {
    if (typeof (report as any).age_hours === 'number') {
      return Math.max(0, Math.round((report as any).age_hours));
    }
    return Math.max(0, Math.round((report.age_days ?? 0) * 24));
  }

  private static _resolveCommitsBehind(report: AuditReport): string | number {
    if (report.commits_behind === Infinity) {
      return '?';
    }
    return typeof report.commits_behind === 'number' ? report.commits_behind : 0;
  }
}
